export const products = 
    [
        {
            id: 'id',
            imgAlt: 'arte-guerra-Sun-Tzu',
            imgLink: 'https://images-americanas.b2w.io/produtos/7475604915/imagens/livro-fisico-a-arte-da-guerra-sun-tzu-trilingue-portugues-ingles-espanhol-seja-um-lider-na-vida-e-no-mundo-corporativo/7475604915_1_large.jpg',
            name: 'A Arte Da Guerra ',
            type: 'NÃO-FICÇÃO',
            overview: '"A guerra é um assunto de importância vital para o Estado; o reino da vida ou da morte; o caminho para a sobrevivência ou a ruína. É indispensável estudá-la profundamente." Sun Tzu',
            price: 9.90,
            discountedPrice: 0,
            productUrl: 'arte-guerra-Sun-Tzu',
        },
        {
            id: 'id',
            imgAlt: '1984-George-Owell',
            imgLink: 'https://images-americanas.b2w.io/produtos/2632619320/imagens/livro-1984-edicao-de-luxo/2632619320_1_large.jpg',
            name: '1984 - George Owell',
            type: 'FICÇÃO CIENTÍFICA',
            overview: 'Publicado em 1949, o texto de Orwell nasceu destinado à polêmica. Traduzido em mais de sessenta países, virou minissérie, filmes, quadrinhos, mangás e até uma ópera. Ganhou holofotes em 1999, quando uma produtora holandesa batizou seu reality show de Big Brother. 1984 foi responsável pela popularização de muitos termos e conceitos, como Grande Irmão, duplopensar, novidioma, buraco da memória e 2 2 5. O trabalho de Winston, o herói de 1984, é reescrever artigos de jornais do passado, de modo que o registro histórico sempre apoie a ideologia do Partido. Grande parte do Ministério também destrói os documentos que não foram revisados, dessa forma não há como provar que o governo esteja mentindo. Winston é um trabalhador diligente e habilidoso, mas odeia secretamente o Partido e sonha com a rebelião contra o Grande Irmão.',
            price: 19.90,
            discountedPrice: 0,
            productUrl: '1984-George-Owell', 
        },
        {
            id: 'id',
            imgAlt: 'Rápido e Devagar: Duas formas de pensar',
            imgLink: 'https://roteirosliterarios.com.br/wp-content/uploads/2024/02/rapido-e-devagar.jpg',
            name: 'Rápido e Devagar: Duas formas de pensar',
            type: 'NÃO-FICÇÃO',
            overview: 'Em Rápido e devagar: duas formas de pensar, Daniel Kahneman nos leva a uma viagem pela mente humana e explica as duas formas de pensar: uma é rápida, intuitiva e emocional; a outra, mais lenta, deliberativa e lógica. Kahneman expõe as capacidades extraordinárias - e também os defeitos e vícios - do pensamento rápido e revela a influência das impressões intuitivas nas nossas decisões. Comportamentos tais como a aversão à perda, o excesso de confiança no momento de escolhas estratégicas, a dificuldade de prever o que vai nos fazer felizes no futuro e os desafios de identificar corretamente os riscos no trabalho e em casa só podem ser compreendidos se soubermos como as duas formas de pensar moldam nossos julgamentos. As questões colocadas por Kahneman se revelam muitas vezes inquietantes: é verdade que o sucesso de um investidor é completamente aleatório e que sua habilidade no mercado financeiro é apenas uma ilusão? Por que o medo de perder é mais forte do que o prazer de ganhar? Kahneman revela quando podemos ou não confiar em nossa intuição. Oferece insights práticos e esclarecedores sobre como tomamos decisões nos negócios e na vida pessoal, e como podemos usar diferentes técnicas para nos proteger contra falhas mentais que muitas vezes nos colocam em apuros.',
            price: 56.99,
            discountedPrice: 39.99,
            productUrl: 'Rápido-devagar-Daniel-Kahneman',
        },
        {
            id: 'id',
            imgAlt: 'Fahrenheit 451',
            imgLink: 'https://a-static.mlcdn.com.br/450x450/livro-fahrenheit-451-edicao-especial/magazineluiza/227263500/d45b90c70418b0129657dafda3ee3f49.jpg',
            name: 'Fahrenheit 451',
            type: 'FICÇÃO CIENTÍFICA',
            overview: 'Guy Montag é um bombeiro. Sua profissão é atear fogo nos livros. Em um mundo onde as pessoas vivem em função das telas e a literatura está ameaçada de extinção, os livros são objetos proibidos, e seus portadores são considerados criminosos. Montag nunca questionou seu trabalho; vive uma vida comum, cumpre o expediente e retorna ao final do dia para sua esposa e para a rotina do lar. Até que conhece Clarisse, uma jovem de comportamento suspeito, cheia de imaginação e boas histórias. Quando sua esposa entra em colapso mental e Clarisse desaparece, a vida de Montag não poderá mais ser a mesma.',
            price: 59.90,
            discountedPrice: 35.62,
            productUrl: 'Fahrenheit-451-Ray-Bradbury',
        },
        {
            id: 'id',
            imgAlt: 'Trilogia 50 Tons de Cinza',
            imgLink: 'https://down-br.img.susercontent.com/file/9df83f0374dcacce51f0d894f16f6749',
            name: 'Trilogia 50 Tons de Cinza',
            type: 'ROMANCE',
            overview: 'Quando Anastasia Steele entrevista o jovem empresário Christian Grey, descobre nele um homem atraente, brilhante e profundamente dominador. Ingênua e inocente, Ana se surpreende ao perceber que, a despeito da enigmática reserva de Grey, está desesperadamente atraída por ele.',
            price: 89.90,
            discountedPrice: 0,
            productUrl: 'trilogia-50-tons-de-cinza',
        },
        {
            id: 'id',
            imgAlt: 'O Código Da Vinci ',
            imgLink: 'https://http2.mlstatic.com/D_NQ_NP_706932-MLB45701794855_042021-O.webp',
            name: 'O Código Da Vinci ',
            type: 'ROMANCE',
            overview: 'Um assassinato dentro do Museu do Louvre, em Paris, traz à tona uma sinistra conspiração para revelar um segredo que foi protegido por uma sociedade secreta desde os tempos de Jesus Cristo. A vítima é o respeitado curador do museu, Jacques Saunière, um dos líderes dessa antiga fraternidade, o Priorado de Sião, que já teve como membros Leonardo da Vinci, Victor Hugo e Isaac Newton.',
            price: 64.80,
            discountedPrice: 0,
            productUrl: 'o-codigo-da-vinci',
        },
        {
            id: '',
            imgAlt: 'Interestelar',
            imgLink: 'https://ae03.alicdn.com/kf/S3849da0529034879a640d1fc5b87dc1aZ.jpg',
            name: 'Interestelar',
            type: 'FICÇÃO CIENTÍFICA',
            overview: '“O FIM DA TERRA NÃO SERÁ O NOSSO FIM”Do aclamado cineasta Christopher Nolan, diretor de A origem (Inception) e da trilogia Batman – O Cavaleiro das Trevas (Batman - The Dark Knight), INTERESTELAR é a crônica de um grupo de exploradores que se aproveita de um recém-descoberto buraco de minhoca para ultrapassar os limites das viagens espaciais tripuladas e assim conquistar as grandes distâncias de uma jornada interestelar. Enquanto viajam, estão em risco o destino do planeta... Terra...e o futuro da raça humana.O livro INTERESTELAR consegue explicar com clareza a teoria do físico Kip Thorne, que inspirou esta incrível história de ficção científica. Não é por nada que o filme, estrelado por Matthew McConaughey e Anne Hathaway, tornou-se imediatamente um cult mundial. No entanto, graças ao livro, com suas 268 páginas, as complexas e sofisticadas teorias desenvolvidas por Kip Thorne ficam accessíveis à maioria dos leitores. O filme, por sua vez, até pela sua própria linguagem e natureza, não consegue "traduzir" toda a profundidade e dimensão da história. Um livro profundo e interessante, para aqueles que viram o filme e para os que se preocupam com o futuro da humanidade.',
            price: 59.90,
            discountedPrice: 51.00,
            productUrl: 'interestelar-Cristopher-Nolan'
        },
        {
            id: '',
            imgAlt: 'Battle Royale',
            imgLink: 'https://a-static.mlcdn.com.br/450x450/livro-battle-royale/magazineluiza/223209700/cc3c6c75f4503ab070d631c77b96438c.jpg',
            name: 'Battle Royale',
            type: 'FICCÇÃO CIENTÍFICA',
            overview: 'Em 1997, o jornalista e escritor japonês Koushun Takami sofreu uma grande decepção. O manuscrito de seu romance de estreia havia chegado à final do Japan Grand Prix Horror Novel, concurso literário voltado para a ficção de terror, mas acabou preterido. Não era para menos. Embora habituado a tramas assustadoras, o júri se alarmou com a história do jogo macabro entre adolescentes de uma mesma turma escolar que, confinados numa ilha, têm de matar uns aos outros até que reste apenas um sobrevivente. Detalhe: o organizador da sangrenta disputa é o próprio Estado japonês, imaginado pelo autor como uma totalitária República da Grande Ásia Oriental.',
            price: 69.50,
            discountedPrice: 0,
            productUrl: 'battle-royale-Koushun-Takami'
        },
        {
            id: '',
            imgAlt: 'A culpa é das estrelas',
            imgLink: 'https://http2.mlstatic.com/D_NQ_NP_948576-MLB47655470258_092021-O.webp',
            name: 'A culpa é das estrelas',
            type: 'ROMANCE',
            overview: 'Hazel é uma paciente terminal. Ainda que, por um milagre da medicina, seu tumor tenha encolhido bastante ― o que lhe dá a promessa de viver mais alguns anos ―, o último capítulo de sua história foi escrito no momento do diagnóstico. Mas em todo bom enredo há uma reviravolta, e a de Hazel se chama Augustus Waters, um garoto bonito que certo dia aparece no Grupo de Apoio a Crianças com Câncer. Juntos, os dois vão preencher o pequeno infinito das páginas em branco de suas vidas. Inspirador, corajoso, irreverente e brutal, A culpa é das estrelas é a obra mais ambiciosa e emocionante de John Green, sobre a alegria e a tragédia que é viver e amar.',
            price: 44.99,
            discountedPrice: 0,
            productUrl: 'a-culpa-e-das-estrelas-john-green'
        },
        {
            id: '',
            imgAlt: 'Amor & Gelato',
            imgLink: 'https://a-static.mlcdn.com.br/450x450/kit-amor-gelato-jenna-evans-welch/institutobeneficenteboanova/84691/92213978695c3f84edd7f0f9a44f1b20.jpeg',
            name: 'Amor & Gelato',
            type: 'ROMANCE',
            overview: "Depois da morte da mãe, Lina fica com a missão de realizar um último pedido: ir até a Itália para conhecer o pai. Do dia para a noite, ela se vê na famosa paisagem da Toscana, morando em uma casa localizada no mesmo terreno de um cemitério memorial de soldados americanos da Segunda Guerra Mundial, com um homem que nunca tinha ouvido falar. Apesar das belezas arquitetônicas, da história da cidade e das comidas maravilhosas, o que Lina mais quer é ir embora correndo dali. Mas as coisas começam a mudar quando ela recebe um antigo diário da mãe. Nele, a menina embarca em uma misteriosa história de amor, que pode explicar suas próprias origens. No meio desse turbilhão de emoções, Lina ainda conhece Ren e Thomas, dois meninos lindos que vão mexer ainda mais com seu coração. Uma trajetória que fará Lina descobrir o amor, a si mesma e também aprender a lidar com a perda. Amor & gelato é uma deliciosa viagem pelos mais românticos pontos turísticos italianos, com direito a tudo de mais intenso que o lugar tem a oferecer: desde paixões até corações partidos.",
            price: 59.90,
            discountedPrice: 41.18,
            productUrl: 'amor-&-gelato-Jenna-Evans-Welch'
        },
        {
            id: '',
            imgAlt: 'A Interpretação dos Sonhos',
            imgLink: 'https://images-americanas.b2w.io/produtos/32241286/imagens/livro-fisico-a-interpretacao-dos-sonhos-sigmund-freud/32241284_1_large.jpg',
            name: 'A Interpretação dos Sonhos',
            type: 'NÃO-FICÇÃO',
            overview: 'Mais do que revolucionar a Psicologia e contribuir para as Neurociências, o conhecimento sistematizado por Sigmund Freud em suas obras revelou um estilo de escrita peculiar, que muito diz sobre o próprio funcionamento da mente proposto por sua Psicanálise. A fala do sujeito é o centro de suas teorias e do trabalho psicanalítico, revelando questões do inconsciente. Ler Freud, então, não é algo que deva estar circunscrito a psicanalistas e psicólogos. A leitura é interessante aos que buscam entender como se dá o uso da própria linguagem. Os caminhos para esse entendimento se revelam à luz da compreensão de diversas patologias mentais estudadas pelo Pai da Psicanálise (e de conceitos já amplamente difundidos, perfeitamente acessíveis nos textos originais de Freud)',
            price: 62.25,
            discountedPrice: 49.80,
            productUrl: 'a-interpretacao-dos-sonhos-Sigmund-Freud'
        },
        {
            id: '',
            imgAlt: 'Assim Falou Zaratustra',
            imgLink: 'https://images-americanas.b2w.io/produtos/3449359857/imagens/livro-fisico-assim-falava-zaratustra-friedrich-nietzsche-pdl/3449359857_1_large.jpg',
            name: 'Assim Falou Zaratustra',
            type: 'NÃO-FICÇÃO',
            overview: 'Um dos trabalhos filosóficos mais lidos e influentes de todos os tempos, Assim falou Zaratustra talvez deva sua extraordinária fortuna ao seu caráter híbrido: filosofia, religião e literatura nele se juntam de maneira complexa e atraente. Ao publicar Além do bem e do mal, livro imediatamente posterior, Nietzsche revelou ao amigo Jacob Burckhardt que a nova publicação continha “as mesmas coisas que havia dito antes pela boca de Zaratustra, mas de modo diferente, bem diferente”. De fato, o leitor reconhecerá, na linguagem metafórica e alegórica dos discursos e diálogos de Zaratustra, muitas das ideias que seriam desenvolvidas em prosa reflexiva nas obras posteriores ― ou que já haviam sido abordadas em Aurora e A gaia ciência, livros aos quais ele chegou a se referir como “comentários ao Zaratustra antes que ele aparecesse”',
            price: 29.90,
            discountedPrice: 0,
            productUrl: 'assim-falou-zaratustra-Friedrich-Nietzsche'
        },
        {
            id: '',
            imgAlt: '',
            imgLink: '',
            name: '',
            type: '',
            overview: '',
            price: 0,
            discountedPrice: 0,
            productUrl: ''
        },
        {
            id: '',
            imgAlt: '',
            imgLink: '',
            name: '',
            type: '',
            overview: '',
            price: 0,
            discountedPrice: 0,
            productUrl: ''
        },
    ]