export const products = 
    [
        {
            id: 'id',
            imgAlt: 'arte-guerra-Sun-Tzu',
            imgLink: 'https://images-americanas.b2w.io/produtos/7475604915/imagens/livro-fisico-a-arte-da-guerra-sun-tzu-trilingue-portugues-ingles-espanhol-seja-um-lider-na-vida-e-no-mundo-corporativo/7475604915_1_large.jpg',
            name: 'A Arte Da Guerra ',
            type: 'NÃO-FICÇÃO',
            overview: '"A guerra é um assunto de importância vital para o Estado; o reino da vida ou da morte; o caminho para a sobrevivência ou a ruína. É indispensável estudá-la profundamente." Sun Tzu',
            price: 9.90,
            discountedPrice: 0,
            productUrl: 'arte-guerra-Sun-Tzu',
        },
        {
            id: 'id',
            imgAlt: '1984-George-Owell',
            imgLink: 'https://images-americanas.b2w.io/produtos/2632619320/imagens/livro-1984-edicao-de-luxo/2632619320_1_large.jpg',
            name: '1984 - George Owell',
            type: 'FICÇÃO CIENTÍFICA',
            overview: 'Publicado em 1949, o texto de Orwell nasceu destinado à polêmica. Traduzido em mais de sessenta países, virou minissérie, filmes, quadrinhos, mangás e até uma ópera. Ganhou holofotes em 1999, quando uma produtora holandesa batizou seu reality show de Big Brother. 1984 foi responsável pela popularização de muitos termos e conceitos, como Grande Irmão, duplopensar, novidioma, buraco da memória e 2 2 5. O trabalho de Winston, o herói de 1984, é reescrever artigos de jornais do passado, de modo que o registro histórico sempre apoie a ideologia do Partido. Grande parte do Ministério também destrói os documentos que não foram revisados, dessa forma não há como provar que o governo esteja mentindo. Winston é um trabalhador diligente e habilidoso, mas odeia secretamente o Partido e sonha com a rebelião contra o Grande Irmão.',
            price: 19.90,
            discountedPrice: 0,
            productUrl: '1984-George-Owell', 
        },
        {
            id: 'id',
            imgAlt: 'Rápido e Devagar: Duas formas de pensar',
            imgLink: 'https://roteirosliterarios.com.br/wp-content/uploads/2024/02/rapido-e-devagar.jpg',
            name: 'Rápido e Devagar: Duas formas de pensar',
            type: 'NÃO-FICÇÃO',
            overview: 'Em Rápido e devagar: duas formas de pensar, Daniel Kahneman nos leva a uma viagem pela mente humana e explica as duas formas de pensar: uma é rápida, intuitiva e emocional; a outra, mais lenta, deliberativa e lógica. Kahneman expõe as capacidades extraordinárias - e também os defeitos e vícios - do pensamento rápido e revela a influência das impressões intuitivas nas nossas decisões. Comportamentos tais como a aversão à perda, o excesso de confiança no momento de escolhas estratégicas, a dificuldade de prever o que vai nos fazer felizes no futuro e os desafios de identificar corretamente os riscos no trabalho e em casa só podem ser compreendidos se soubermos como as duas formas de pensar moldam nossos julgamentos. As questões colocadas por Kahneman se revelam muitas vezes inquietantes: é verdade que o sucesso de um investidor é completamente aleatório e que sua habilidade no mercado financeiro é apenas uma ilusão? Por que o medo de perder é mais forte do que o prazer de ganhar? Kahneman revela quando podemos ou não confiar em nossa intuição. Oferece insights práticos e esclarecedores sobre como tomamos decisões nos negócios e na vida pessoal, e como podemos usar diferentes técnicas para nos proteger contra falhas mentais que muitas vezes nos colocam em apuros.',
            price: 56.99,
            discountedPrice: 39.99,
            productUrl: 'Rápido-devagar-Daniel-Kahneman',
        },
        {
            id: 'id',
            imgAlt: 'Fahrenheit 451',
            imgLink: 'https://a-static.mlcdn.com.br/450x450/livro-fahrenheit-451-edicao-especial/magazineluiza/227263500/d45b90c70418b0129657dafda3ee3f49.jpg',
            name: 'Fahrenheit 451',
            type: 'FICÇÃO CIENTÍFICA',
            overview: 'Guy Montag é um bombeiro. Sua profissão é atear fogo nos livros. Em um mundo onde as pessoas vivem em função das telas e a literatura está ameaçada de extinção, os livros são objetos proibidos, e seus portadores são considerados criminosos. Montag nunca questionou seu trabalho; vive uma vida comum, cumpre o expediente e retorna ao final do dia para sua esposa e para a rotina do lar. Até que conhece Clarisse, uma jovem de comportamento suspeito, cheia de imaginação e boas histórias. Quando sua esposa entra em colapso mental e Clarisse desaparece, a vida de Montag não poderá mais ser a mesma.',
            price: 59.90,
            discountedPrice: 35.62,
            productUrl: 'Fahrenheit-451-Ray-Bradbury',
        },
        {
            id: 'id',
            imgAlt: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08651c_a_107x1_1_2.png?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:&format=jpeg',
            name: 'Converse X Martine Ali Chuck 70 Xhi Preto',
            type: 'UNISEX CANO ALTO',
            overview: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 1090.00,
            discountedPrice: 0,
            productUrl: 'converse-x-martine-ali-chuck-70-xhi-preto',
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08102c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Modern Lift Chrome Queen Preto',
            type: 'FEMININO CANO ALTO',
            overview: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 599.90,
            discountedPrice: 0,
            productUrl: 'chuck-taylor-all-star-modern-lift-chrome-queen-preto',
        },
        {
            id: 'id',
            imgAlt: 'Tênis Converse Chuck Taylor All Star Hi Future Utility',
            imgLink: 'https://espacotenis.vteximg.com.br/arquivos/ids/171907-1000-1000/converse-hi-future-utility-branco.jpg?v=638191505258630000',
            name: 'Converse Chuck Taylor All Star Hi Future Utility',
            type: 'UNISEX CANO ALTO',
            overview: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 449.90,
            discountedPrice: 349.90,
            productUrl: 'tenis-coverse-chuck-taylor-all-star-hi-future-utility',
        },
        {
            id: 'id',
            imgAlt: 'Vans Classic',
            imgLink: 'https://www.tradeinn.com/f/125/1252969/vans-sapatos-sem-cadarco-classic.jpg',
            name: 'Vans  Classic',
            type: 'UNISEX CANO BAIXO',
            overview: 'OFF THE WALL',
            price: 249.90,
            discountedPrice: 0,
            productUrl: 'vans-sem-cadarço-classic',
        },
        {
            id: 'id',
            imgAlt: 'Tênis Nike Air Max 97',
            imgLink: 'https://images.tcdn.com.br/img/img_prod/1048024/tenis_nike_air_max_97_branco_921826_101_6729_1_1ed3ff085def62045397ec3725058f42.jpg',
            name: 'Tênis Nike Air Max 97',
            type: 'UNISEX CANO BAIXO',
            overview: 'JUST DO IT',
            price: 1049.90,
            discountedPrice: 849.90,
            productUrl: 'tenis-nike-air-max-97',
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star Chrome Queen Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06444c_a_107x1_6.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star Chrome Queen Branco',
            type: 'UNISEX CANO ALTO',
            overview: 'Libere seu lado punk no estilo assinado por Chuck Taylor',
            price: 549.90,
            discountedPrice: 0,
            productUrl: 'chuck-taylor-all-star-chrome-queen-branco',
        },
        {
            id: 'id',
            imgAlt: 'Vans Benegas X Enarson White',
            imgLink: 'https://www.tillys.com/on/demandware.static/-/Sites-master-catalog/default/dw51976e42/tillys/images/catalog/1000x1000/267631150a.jpg',
            name: 'Vans Benegas X Enarson White',
            type: 'UNISEX CANO BAIXO',
            overview: 'OFF THE WALL',
            price: 599.90,
            discountedPrice: 0,
            productUrl: 'vans-hi-benegas-x-enarson-white',
        },
        {
            id: 'id',
            imgAlt: 'Slacker-160',
            imgLink: 'https://demoniacult.com/cdn/shop/products/slacker-160-w_640x640_crop_center.jpg?v=1628719610',
            name: 'Slacker-160',
            type: 'FEMININO CANO ALTO',
            overview: 'Definindo moda alternativa',
            price: 615.00,
            discountedPrice: 0,
            productUrl: 'slacker-160w',
        },
        {
            id: 'id',
            imgAlt: 'Camel-311',
            imgLink: 'https://demoniacult.com/cdn/shop/products/camel-311-wpu_85460dbe-f010-41d7-8b82-71b586fadd36_640x640_crop_center.jpg?v=1633036501',
            name: 'Camel-11',
            type: 'FEMININO CANO ALTO',
            overview: 'Definindo moda alternativa',
            price: 690.00,
            discountedPrice: 0,
            productUrl: 'camel-311wpu',
        },
        {
            id: 'id',
            imgAlt: 'Gravedigger-250',
            imgLink: 'https://demoniacult.com/cdn/shop/products/gravedigger-250-bvl_640x640_crop_center.jpg?v=1582160150',
            name: 'Gravedigger-250',
            type: 'FEMININO CANO ALTO',
            overview: 'Definindo moda alternativa',
            price: 805.00,
            discountedPrice: 0,
            productUrl: 'gravedigger-250bvl',
        },
        {
            id: 'id',
            imgAlt: 'Shaker-70',
            imgLink: 'https://demoniacult.com/cdn/shop/products/shaker-70-bvl_640x640_crop_center.jpg?v=1612829860',
            name: 'Shaker-70',
            type: 'FEMININO CANO ALTO',
            overview: 'Definindo moda alternativa',
            price: 680.00,
            discountedPrice: 0,
            productUrl: 'shaker-70',
        },
        {
            id: 'id',
            imgAlt: 'Shaker-52',
            imgLink: 'https://demoniacult.com/cdn/shop/products/shaker-52-wvl_640x640_crop_center.jpg?v=1633036981',
            name: 'Shaker-52',
            type: 'FEMININO CANO ALTO',
            overview: 'Definindo moda alternativa',
            price: 535.00,
            discountedPrice: 0,
            productUrl: 'shaker-52',
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star City Trek Marrom',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06601c_a_107x1_3.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star City Trek Marrom',
            type: 'MASCULINO CANO ALTO',
            overview: 'Defina o seu padrão audacioso com esse icônico All Stat City Trek.',
            price: 499.90,
            discountedPrice: 0,
            productUrl: 'chuck-taylor-all-star-city-trek-cano-alto-normal-marrom',
        },
        {
            id: 'id',
            imgAlt: 'Chuck Taylor All Star City Trek Cinza',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a06558c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck Taylor All Star City Trek Cinza',
            type: 'MASCULINO CANO ALTO',
            overview: 'Enfrente terrenos urbanos imprevisíveis em tênis de cano alto que oferecem conforto e estilo confiáveis.',
            price: 499.90,
            discountedPrice: 0,
            productUrl: 'chuck-taylor-all-star-city-trek-cano-alto-normal-cinza',
        },
        {
            id: 'id',
            imgAlt: 'Chuck 70 Garden Starter Waxed Canvas Marrom',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09157c_a_107x1_1_5.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck 70 Garden Starter Waxed Canvas Marrom',
            type: 'MASCULINO CANO ALTO',
            overview: 'Esses Chucks adoram jardinagem, e você também.',
            price: 599.90,
            discountedPrice: 0,
            productUrl: 'chuck-70-garden-starter-waxed-canvas-cano-alto-grande-marrom',
        },
        {
            id: 'id',
            imgAlt: 'Chuck 70 Garden Starter Waxed Canvas Amarelo',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09158c_a_107x1_8.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Chuck 70 Garden Starter Waxed Canvas Amarelo',
            type: 'MASCULINO CANO ALTO',
            overview: 'Esses Chucks adoram jardinagem, e você também.',
            price: 599.90,
            discountedPrice: 0,
            productUrl: 'chuck-70-garden-starter-waxed-canvas-cano-alto-grande-amarelo',
        },
        {
            id: 'id',
            imgAlt: 'Pro Blaze V2 Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/c/o/co04930002-2_a_08x1_2__2.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Pro Blaze V2 Preto',
            type: 'MASCULINO CANO BAIXO',
            overview: 'Vista-se com algo ousado, como este icônico Pro Blaze, feito todo de material sintético.',
            price: 379.90,
            discountedPrice: 0,
            productUrl: 'pro-blaze-v2-cano-baixo-normal-preto',
        },
        {
            id: 'id',
            imgAlt: 'Pro Blaze V2 Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/c/o/co04930003_a_107x1_9.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Pro Blaze V2 Branco',
            type: 'MASCULINO CANO BAIXO',
            overview: 'Vista-se com algo ousado, como este icônico Pro Blaze, feito todo de material sintético.',
            price: 379.90,
            discountedPrice: 0,
            productUrl: 'pro-blaze-v2-cano-baixo-normal-branco',
        },
        //--------------------------LIMITED-EDITION--------------------------
        {
            id: 'id',
            imgAlt: 'Converse X Comme Des Garçons Play Chuck 70 Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/1/5/150204c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Converse X Comme Des Garçons Play Chuck 70 Preto',
            type: 'LIMITADO MASCULINO CANO ALTO',
            overview: 'Siga seu coração com o tênis Converse x PLAY Comme des Garçons Chuck 70.',
            price: 899.90,
            discountedPrice: 0,
            productUrl: 'converse-x-comme-des-garcons-play-chuck-70-cano-alto-preto',
        },
        {
            id: 'id',
            imgAlt: 'Converse x Comme des Garçons PLAY Chuck 70 Azul',
            imgLink: 'https://converse.com.br/media/catalog/product/1/7/171846c_c1_107x1_1_14.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Converse x Comme des Garçons PLAY Chuck 70 Azul',
            type: 'LIMITADO MASCULINO CANO ALTO',
            overview: 'O logo de coração e olhinhos à espreita está de volta no Chuck 70 em dois novos tons sazonais.',
            price: 899.90,
            discountedPrice: 0,
            productUrl: 'converse-x-comme-des-garcons-play-chuck-70-cano-alto-grande-azul',
        },
        {
            id: 'id',
            imgAlt: 'Converse X COMME DES GARÇONS* Multi Heart Chuck 70 Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a08148c_a_107x1_9.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Converse X COMME DES GARÇONS* Multi Heart Chuck 70 Branco',
            type: 'LIMITADO UNISEX CANO ALTO',
            overview: 'Siga seu coração com o Converse x Comme des Garçons PLAY Chuck 70.',
            price: 899.90,
            discountedPrice: 0,
            productUrl: 'converse-x-comme-des-garcons-multi-heart-chuck-70-branco-cano-alto-grande-branco',
        },
        {
            id: 'id',
            imgAlt: 'Dungeons & Dragons X Converse Chuck Taylor All Star Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09885c_a_08x1_6_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Dungeons & Dragons X Converse Chuck Taylor All Star Preto',
            type: 'LIMITADO UNISEX CANO ALTO',
            overview: 'A Converse comemora 50 anos do RPG Dungeons & Dragons com Chucks de edição limitada, trazendo a tela clássica para as aventuras épicas de D&D.',
            price: 499.90,
            discountedPrice: 0,
            productUrl: 'dungeons-dragons-x-converse-chuck-taylor-all-star-cano-alto-grande-preto',
        },
        {
            id: 'id',
            imgAlt: 'Dungeons & Dragons X Converse Chuck 70 Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09883c_a_107x1_white_4_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Dungeons & Dragons X Converse Chuck 70 Preto',
            type: 'LIMITADO UNISEX CANO ALTO',
            overview: 'A Converse comemora 50 anos de Dungeons & Dragons com uma edição limitada do Chuck 70, trazendo o ícone favorito dos fãs para o mundo de fantasia do lendário RPG.',
            price: 699.90,
            discountedPrice: 0,
            productUrl: 'dungeons-dragons-x-converse-chuck-70-cano-alto-grande-preto',
        },
        {
            id: 'id',
            imgAlt: 'Dungeons & Dragons X Converse Chuck 70 Branco',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09884c_a_107x1_white_4_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Dungeons & Dragons X Converse Chuck 70 Branco',
            type: 'LIMITADO UNISEX CANO ALTO',
            overview: 'A Converse comemora 50 anos de Dungeons & Dragons com um Chuck 70 de couro de edição limitada, trazendo o ícone favorito dos fãs para o mundo de fantasia do lendário RPG.',
            price: 749.90,
            discountedPrice: 0,
            productUrl: 'dungeons-dragons-x-converse-chuck-70-cano-alto-grande-branco',
        },
        {
            id: 'id',
            imgAlt: 'Dungeons & Dragons X Converse Chuck Taylor All Star Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/a/0/a09886c_a_107x1_4_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'Dungeons & Dragons X Converse Chuck Taylor All Star Preto',
            type: 'LIMITADO UNISEX CANO ALTO',
            overview: 'Converse comemora 50 anos do RPG Dungeons & Dragons com Chucks de edição limitada, trazendo a tela clássica para as aventuras épicas de D&D.',
            price: 499.90,
            discountedPrice: 0,
            productUrl: 'dungeons-dragons-x-converse-chuck-taylor-all-star-cano-alto-grande-ci05030001-preto',
        },
        {
            id: 'id',
            imgAlt: 'One Star Pro Preto',
            imgLink: 'https://converse.com.br/media/catalog/product/1/7/171327c_a_107x1_1.jpg?optimize=high&bg-color=255,255,255&fit=bounds&height=&width=&canvas=:',
            name: 'One Star Pro Preto',
            type: 'MASCULINO CANO BAIXO',
            overview: 'Estilo ou desempenho? O One Star Pro oferece os dois.',
            price: 549.90,
            discountedPrice: 0,
            productUrl: 'one-star-pro-cano-baixo-normal-preto',
        },
    ]